=== Nico-Bedia/lmsgi/UD3/UT3_A05/Actividad05_DTD/anuario2.dtd
<!ELEMENT anuario (articulo+)>
<!ATTLIST anuario aÃ±o CDATA #REQUIRED>
<!ELEMENT articulo (titulo, fecha, numLectores, autores)>
<!ATTLIST articulo identificador CDATA #REQUIRED>

<!ELEMENT titulo (#PCDATA)>
<!ELEMENT fecha (#PCDATA)>
<!ELEMENT numLectores (#PCDATA)>

<!ELEMENT autores (autor+)>
<!ELEMENT autor EMPTY>
<!ATTLIST autor nombre CDATA #REQUIRED>
<!ATTLIST autor mail CDATA #REQUIRED>

=== Nico-Bedia/lmsgi/UD3/UT3_A05/Actividad05_DTD/anuario.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE anuario SYSTEM "./anuario2.dtd">
<anuario año="2018">
    <articulo identificador="A-6785">        
        <titulo>Microsoft quiere comerse a Slack</titulo>
        <fecha>2018-01-10</fecha>
        <numLectores>25000</numLectores>
        <autores>
            <autor nombre="Pedro Picapiedra" mail="jimenez@aruario.es" />
            <autor nombre="Alonso Pérez" mail="rosamar@exterior.es"/>
        </autores>        
    </articulo>
    <articulo identificador="C-0780">        
        <titulo>Regalos para padres techies</titulo>
        <fecha>2018-01-20</fecha>
        <numLectores>25000</numLectores>
        <autores>
            <autor nombre="Pedro Picapiedra" mail="jimenez@aruario.es"/>
            <autor nombre="Alonso Pérez" mail="rosamar@exterior.es"/>
        </autores>        
    </articulo>
</anuario>
